<?php

class Api_Supplier_Options extends PhalApi_Api
{
    public function getRules()
    {
        return parent::getRules(); // TODO: Change the autogenerated stub
    }

    public function go(){
        $rs = array('code'=>0,'content'=>'','msg'=>'');

        $domain = new Domain_Supplier_Options();

        $options = $domain->get();

        $rs['code'] = 1;
        $rs['content'] = $options;

        return $rs;
    }
}