<?php

//复制订单model
class Model_OrderCopy extends PhalApi_Model_NotORM
{
    private $_tableName = '';
    private $_tableKey = '';

    public function __construct($tableName,$tableKey)
    {
        $this->_tableName = $tableName;
        $this->_tableKey = $tableKey;
    }

    public function getTableKey($table)
    {
        return $this->_tableKey; // TODO: Change the autogenerated stub
    }

    public function getTableName($id)
    {
        return $this->_tableName;
    }
}